apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-react-deployment
  labels:
    component: front-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      component: front-deployment
  template:
    metadata:
      name: react-pod
      labels:
        component: front-deployment
    spec:
      containers:
        - name: react-container
          image: sassisam/reactapp
          ports:
            - containerPort: 3000