apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  type: NodePort
  ports:
    - port: 3050
      targetPort: 3000 
      nodePort: 32004
  selector:
    component: front-deployment
